dist: xenial
language: python
python:
- 3.7.2
install:
- pip install -r requirements.txt
script:
- pytest

deploy:
  provider: pypi
  user: lucasrodes
  password:
    secure: kFbNLYSQH27OvIqzJvG7OAyIfLJfVsZEsvKkf9JtK5nkk6mYCp+8cmM9uMJyMDNnI6tzp3NCSe7O2X/Qpi8PXIBBYEQVMsKQw4ayT2/o4qislDNquPZFWyZ8NRciWuH+72uAPzVjTZtzk3PuaZxz/SQFcYyNtFpxKHlRLgCJWJl0XDmGnBIAToNliX/N007GsSlcKcUl8JCL8BJeOqoIuU5nkqsjDxZInQlrX1WEPsu4/teCLoE0/ELxmx480i6S4F3JPTNcen58z9GFlBoMKFKHq3kZHJSUtXgCg4M7MPHLgmXIslktN5TgN2+rNBTt/3oDBJW4+i6yvTrw/dDzwfY8omNccXZQUd9iCJLX9al7/qwB90WOmfKTdSXhOZAEO0YEiK6IYYIz+GqQykZ+FZiIbcu7MEy55EiFY+mTL3yYxo7nnWzTdi7P1Mf8/padZ+BaQfR3u+bAN3Cogx4HnlTnUR2XOCfftQyMs6zhm2ldSYjqF3D5dvq6Vn6VLjx7x/qtlSNMXMZLD6FOvrLJXmcAKqPLtQjV+Bb7wnDY9ye+N9r22AkeG/f8E+NEdYv1fufMaJe4/zn8BLgnNOB88o/ztW/+L+I2k1mRiB4gD/niBDy5Do6rg0XkpGgwrU9fPMjBRtDkrDerJKrHkp2XknezAB1HztR1Xqdj17d9Ddg=