dist: xenial
language: python
python:
  - 3.7.2
  - 3.8
before_install:
  - pip install -r requirements-test.txt
install:
  - ls -l
  - pip uninstall whatstk
  - pip install -e .
  - mkdir tests/chats/
  - whatstk-generate-chats --size 500 tests/chats/  # Generate chats
#pip install -r requirements.txt 
script:
  - pytest --cov-report term --cov=whatstk tests/
after_success:
  - codecov # submit coverage
  # add docs step
deploy:
  provider: pypi
  user: $USER_PYPI
  password: $PWD_PYPI
  on:
    tags: true
