dist: xenial
language: python
python:
  - 3.7.2
  - 3.8
before_install:
  - pip install -r requirements-test.txt
  - pip install -r requirements-flake.txt
install:
  - ls -l
  - pip uninstall whatstk
  - pip install -e .
  - mkdir -p tests/chats/hformats tests/chats/merge
  - whatstk-generate-chats --size 500 --output-path tests/chats/hformats/  # Generate chats for hformat checks
  - whatstk-generate-chats --size 300 --last-timestamp 2019-09-01 --hformats '%Y-%m-%d, %H:%M - %name:' --output-path tests/chats/merge/ --filenames file1.txt
  - whatstk-generate-chats --size 300 --last-timestamp 2020-01-01 --hformats '%Y-%m-%d, %H:%M - %name:' --output-path tests/chats/merge/ --filenames file2.txt
#pip install -r requirements.txt 
script:
  - pytest --cov-report term --cov=whatstk tests/
  - flake8 --max-complexity=10 --docstring-convention=google whatstk

after_success:
  - codecov # submit coverage
  # add docs step
deploy:
  provider: pypi
  user: $USER_PYPI
  password: $PWD_PYPI
  on:
    tags: true
