dist: xenial
language: python
python:
- 3.7.2
- 3.8
install:
- pip install .
script:
- pytest
deploy:
  provider: pypi
  user: lucasrodes
  password:
    secure: z0Phj0i34mGtRYMyTZsc/5PGC7se0U3O5E7YCOUg/14JCcRTZoqd4U4XPU0VchH3cgLax2p8xHnVJ3n1VcgBdEiuBGyU6xNacgPanONBFGk479S5wAPA6cTVvYarDZ9Oh5/f8JmP+WiqZUzLJQtoFprf1xjpOq5SECynx45+o/XJOcAL0JbNAV2C00WZG/lbRayESX+5EwIv0NzXki8aouJQMBklCvbp0I/kEc3xBsAavQdqji6/6169YZ+B0IuyjRq2SCvqNtmvxNScqn/Mvov1qSnuZ0ljxU0bG2StPyfA6cY5h9J3L9IuqrXMeJmY79aCL6xWZzv7emBMn0Q5Ly3wpiv2nnznhOVRzoDz5YptrNm45P/M0qiYtw+1pHRpHVjZ5LlSAVsIGNfjhvlsZw7ZzI70+WziW9v/+UszwURABrggE/kfAMeMjKTfRtXbPXqE0XApubdJrS9hiGHcaqkJVOasDB5zr7lkAg4bcDIyYsU9oGhcC5UKqn/jF0VcXyUoF4UFuuqNg+MjP1B96FMPdbWc1R9XEkYuqSva3fXehPw6RB/P5DGt8neBHywkuKsuUkxlOLBFdurS0O4i6dUZh4uXoDYQHM0brYo3U43yzTUR4CDQzazNVeg3kCj08eF8lvmf6H7OGSaWmQpyMvavb5vITPfS9v+UyOEjZ84=
  on:
    tags: true
